export const ENV_KEYS = {
	NODE_ENV: 'NODE_ENV',
	BACKEND_PORT: 'BACKEND_PORT',
	FRONTEND_URL: 'FRONTEND_URL',
	DATABASE_URL: 'DATABASE_URL',
	JWT_SECRET: 'JWT_SECRET',
	JWT_EXPIRES_IN: 'JWT_EXPIRES_IN',
	REFRESH_JWT_SECRET: 'REFRESH_JWT_SECRET',
	REFRESH_JWT_EXPIRES_IN: 'REFRESH_JWT_EXPIRES_IN',
	KEYCLOAK_AUTH_SERVER_URL: 'KEYCLOAK_AUTH_SERVER_URL',
	KEYCLOAK_REALM: 'KEYCLOAK_REALM',
	KEYCLOAK_CLIENT_ID: 'KEYCLOAK_CLIENT_ID',
	KEYCLOAK_CLIENT_SECRET: 'KEYCLOAK_CLIENT_SECRET',
	KEYCLOAK_PORT: 'KEYCLOAK_PORT',
} as const;

export type EnvKey = keyof typeof ENV_KEYS;
